CREATE TABLE IF NOT EXISTS categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  type TEXT NOT NULL CHECK (type IN ('Expense', 'Income')),
  is_active INTEGER NOT NULL DEFAULT 1,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS subcategories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_id BIGINT NOT NULL REFERENCES categories(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  is_active INTEGER NOT NULL DEFAULT 1,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS payment_methods (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  is_active INTEGER NOT NULL DEFAULT 1,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  default_category_id BIGINT REFERENCES categories(id),
  default_subcategory_id BIGINT REFERENCES subcategories(id),
  usage_count INTEGER NOT NULL DEFAULT 1,
  last_used_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_amount NUMERIC NOT NULL DEFAULT 0,
  average_amount NUMERIC NOT NULL DEFAULT 0,
  first_used_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type TEXT NOT NULL CHECK (type IN ('Expense', 'Income')),
  category_id BIGINT NOT NULL REFERENCES categories(id),
  subcategory_id BIGINT REFERENCES subcategories(id),
  item_name TEXT NOT NULL,
  item_id BIGINT REFERENCES items(id),
  amount NUMERIC NOT NULL CHECK (amount > 0),
  transaction_date DATE NOT NULL,
  payment_method_id BIGINT REFERENCES payment_methods(id),
  notes TEXT NOT NULL DEFAULT '',
  tags TEXT NOT NULL DEFAULT '',
  vendor_or_customer TEXT NOT NULL DEFAULT '',
  deleted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS recurring_rules (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  type TEXT NOT NULL CHECK (type IN ('Expense', 'Income')),
  category_id BIGINT REFERENCES categories(id),
  subcategory_id BIGINT REFERENCES subcategories(id),
  item_name TEXT NOT NULL,
  expected_amount NUMERIC NOT NULL,
  frequency_days INTEGER NOT NULL,
  frequency_label TEXT NOT NULL,
  last_occurred_date DATE,
  next_due_date DATE,
  is_active INTEGER NOT NULL DEFAULT 1,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS settings (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_transactions_date ON transactions(transaction_date);
CREATE INDEX IF NOT EXISTS idx_transactions_category ON transactions(category_id);
CREATE INDEX IF NOT EXISTS idx_transactions_deleted ON transactions(deleted_at);
CREATE INDEX IF NOT EXISTS idx_items_usage ON items(usage_count DESC, last_used_at DESC);

INSERT INTO categories (name, type)
SELECT defaults.name, defaults.type
FROM (VALUES
  ('Business Expense', 'Expense'),
  ('Home Expense', 'Expense'),
  ('Business Income', 'Income'),
  ('Other Income', 'Income')
) AS defaults(name, type)
WHERE NOT EXISTS (
  SELECT 1 FROM categories existing WHERE existing.name = defaults.name
);

INSERT INTO subcategories (category_id, name)
SELECT c.id, s.name
FROM categories c
JOIN (VALUES
  ('Business Expense', 'Raw Material'), ('Business Expense', 'Electricity Bill'),
  ('Business Expense', 'WiFi / Internet'), ('Business Expense', 'Miscellaneous'),
  ('Business Expense', 'Printing'), ('Business Expense', 'Maintenance'),
  ('Business Expense', 'Equipment'), ('Business Expense', 'Transportation'),
  ('Business Expense', 'Labour'), ('Business Expense', 'Rent'),
  ('Business Expense', 'Packaging'), ('Business Expense', 'Stationery'),
  ('Business Expense', 'Software'), ('Business Expense', 'Marketing'),
  ('Business Expense', 'Other'), ('Home Expense', 'Grocery'),
  ('Home Expense', 'Gas Bill'), ('Home Expense', 'Electricity Bill'),
  ('Home Expense', 'WiFi / Internet'), ('Home Expense', 'Travel'),
  ('Home Expense', 'Hospital'), ('Home Expense', 'Miscellaneous'),
  ('Business Income', 'Printing Orders'), ('Business Income', 'Binding'),
  ('Business Income', 'Xerox'), ('Business Income', 'Visiting Cards'),
  ('Business Income', 'Pamphlets'), ('Business Income', 'Brochures'),
  ('Business Income', 'Stamps'), ('Business Income', 'Other'),
  ('Other Income', 'Freelance'), ('Other Income', 'Investments'),
  ('Other Income', 'Rental'), ('Other Income', 'Other')
) AS s(category_name, name) ON c.name = s.category_name
WHERE NOT EXISTS (
  SELECT 1 FROM subcategories existing
  WHERE existing.category_id = c.id AND existing.name = s.name
);

INSERT INTO payment_methods (name)
VALUES ('Cash'), ('UPI'), ('Bank Transfer'), ('Card'), ('Other')
ON CONFLICT (name) DO NOTHING;

INSERT INTO settings (key, value)
VALUES
  ('currency_symbol', '₹'),
  ('currency_code', 'INR'),
  ('app_title', 'Expense & Profit Tracker')
ON CONFLICT (key) DO NOTHING;